spring:
  application:
    name: classinteraction
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        concurrency: 2
        max-concurrency: 4 
server:
  port: 8080
 
eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: /actuator/info
    #health-check-url-path: /actuator/health
  client: 
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/  #http://114.115.207.28:8081/eureka/
    register-with-eureka: true # 不作为Eureka服务注册   
  
custom: 
  token: 
    publicKey: EC86@34$123c
    userClaim: userInfo
    headerKey: accessToken
  ws:
    endpoint: /course #websocket端点路径
    sub: 
      student: 
        classInfoPre: /topic/group/student/ #订阅某个班级的信息前缀
        courseIntercationPre: /topic/course/student/ #订阅某个课程的信息前缀
      teacher:
        csChangePre: /queue/course/teacher/cs/ #订阅某堂课统计并数据更新的消息前缀
        qcChangePre: /queue/course/teacher/qs/ #订阅某堂课题目统计数据更新的消息前缀
  mq: 
    consumer: 
      queue-name:
        course-start: course.start.classinteraction
        course-statistics: course.statistics.classinteraction
        question-pubilish: course.question.pub.classinteraction
        question-statistics: course.question.statistics.classinteraction
        question-termin: course.question.termin.classinteraction
        answer-share: course.question.answer.share.classinteraction
    producer: 
      queue-name:
        course-studentAdd: course.student.add.coursestatistics
        
