spring:
  application:
    name: userservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/school
server:
  port: 8083

eureka: 
  client:    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #instance:
    #ip-address: 114.115.207.28
    #prefer-ip-address: true

com:
  jichuangsi:
    school:
      token:
          jwt:
            secret: EC86@34$123c
          userClaim : userInfo
      swagger:
        enable: true
      message:
        image:
          domain: http://download.jichuangsi.com/m/i/
          path: d:/code/jichuangsi/download/m/i
          dateFormat: yyyyMMdd